edemy_facebook_login:
    path:           /facebook/login
    defaults:       { _controller: edemy.main:indexAction }
    methods:        [ GET ]

edemy_facebook_likes:
    path:           /admin/es/facebook/likes
    defaults:       { _controller: edemy.facebook:likesAction }
    methods:        [ GET ]

edemy_facebook_promo:
    path:           /fb/promo/{id}
    defaults:       { _controller: edemy.main:indexAction, id:1 }
    methods:        [ GET ]

edemy_facebook_privacy:
    path:           /fb/privacidad
    defaults:       { _controller: edemy.main:indexAction }
    methods:        [ GET ]
