services:
    edemy.fb:
        class: eDemy\FbBundle\Controller\FbController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

#    edemy.getlikes:
#        class: eDemy\FbBundle\Command\GetLikesCommand
